name:  Windows Release Builder

# Trigger on every new tag creation
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-**
      - '[0-9]+.[0-9]+.[0-9]+-**'

jobs:
  build:
    runs-on: windows-latest  
    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
           
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
      
    - name: Build the sideload solution
      run: |
        msbuild $((Get-Item *.sln).Name) `
        -v:diag `
        -p:Configuration=Release `
        -p:Platform=x64 `
        -p:AppxBundle=Always `
        -p:AppxBundlePlatforms="x86|x64|ARM" `
        -p:UapAppxPackageBuildMode=$env:BuildMode `
        -p:AppxPackageDir=C:\DeployOutput `
        -p:AppxPackageSigningEnabled=false `
        -restore
      env:
        BuildMode: SideloadOnly
    
    - name: Create archive
      id: archive
      run: |
        $build = Get-ChildItem C:\DeployOutput\
        $archive = $build | Compress-Archive -DestinationPath "$build.zip" -PassThru
        Write-Output "::set-output name=path::$archive"

    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.archive.outputs.path }}
        artifactContentType: application/zip
        tag: ${{ steps.tag.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
